[project]
site_name = "PC_Shop"
site_description = "Интернет-магазин компьютерной техники на Django"
site_author = "Владимир"
docs_dir = "docs"
site_dir = "site"

nav = [
   "index.md",
    "features.md",
   "models.md",
    "install.md",
    "tech.md",
]